/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgtry;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sinon
 */
public class System extends javax.swing.JFrame {

    /**
     * Creates new form test2
     */
    public System() {
        initComponents();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpatientno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpatientname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpatientage = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl1 = new javax.swing.JTable();
        btadd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgtry/Hospital.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 26, -1, 78));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setText("Hospital Data Information System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, 36));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Patient No:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 158, -1, -1));

        txtpatientno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpatientno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtpatientno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpatientnoActionPerformed(evt);
            }
        });
        getContentPane().add(txtpatientno, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 189, 202, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Patient Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 234, -1, -1));

        txtpatientname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpatientname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtpatientname, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 265, 202, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Patient Age:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 310, -1, -1));

        txtpatientage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpatientage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtpatientage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpatientageActionPerformed(evt);
            }
        });
        getContentPane().add(txtpatientage, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 341, 202, -1));

        jtbl1.setBorder(new javax.swing.border.MatteBorder(null));
        jtbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient No", "Patient Name", "Patient Age"
            }
        ));
        jtbl1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jtbl1.setShowGrid(true);
        jtbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbl1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, 107));

        btadd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btadd.setText("Add");
        btadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });
        getContentPane().add(btadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 52, 32));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, 52, 32));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Delete");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 499, 52, 32));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgtry/R.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpatientnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpatientnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpatientnoActionPerformed

    private void txtpatientageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpatientageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpatientageActionPerformed

    private void jtbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblmodel = (DefaultTableModel)jtbl1.getModel();
        String tblDoctorNo = tblmodel.getValueAt(jtbl1.getSelectedRow(),0).toString();
        String tblDoctorName = tblmodel.getValueAt(jtbl1.getSelectedRow(),0).toString();
        String tblDoctorAge = tblmodel.getValueAt(jtbl1.getSelectedRow(),0).toString();

        txtpatientno.setText(tblDoctorNo);
        txtpatientname.setText(tblDoctorName);
        txtpatientage.setText(tblDoctorAge);
    }//GEN-LAST:event_jtbl1MouseClicked

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        // TODO add your handling code here:
        if(txtpatientno.getText().equals("")||txtpatientname.getText().equals("")||txtpatientage.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Enter the Data");
        }
        else
        {
            String data[] = {txtpatientno.getText(),txtpatientname.getText(),txtpatientage.getText()};
            DefaultTableModel tblmodel = (DefaultTableModel)jtbl1.getModel();
            tblmodel.addRow(data);
            txtpatientname.setText("");
            txtpatientno.setText("");
            txtpatientage.setText("");

        }
    }//GEN-LAST:event_btaddActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblmodel = (DefaultTableModel)jtbl1.getModel();
        if(jtbl1.getSelectedRowCount()==1)
        {
            String DoctorNo = txtpatientno.getText();
            String DoctorName = txtpatientname.getText();
            String DoctorAge = txtpatientage.getText();

            tblmodel.setValueAt(DoctorNo,jtbl1.getSelectedRow(),0);
            tblmodel.setValueAt(DoctorName,jtbl1.getSelectedRow(),0);
            tblmodel.setValueAt(DoctorAge,jtbl1.getSelectedRow(),0);
            JOptionPane.showMessageDialog(this,"Record Updated Successfully");

        }
        else
        {
            if(jtbl1.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(this,"Table is Empty");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Please Select Row to Update");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblmodel = (DefaultTableModel)jtbl1.getModel();
        if(jtbl1.getSelectedRowCount()==1)
        {
            tblmodel.removeRow(jtbl1.getSelectedRow());
        }
        else
        {
            if(jtbl1.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(this,"Table is Empty");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Please Select Row to Delete");

            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbl1;
    private javax.swing.JTextField txtpatientage;
    private javax.swing.JTextField txtpatientname;
    private javax.swing.JTextField txtpatientno;
    // End of variables declaration//GEN-END:variables
}
